...

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,91 +30,91 @@ env:
   # TEST_FILTER: foo
 
 jobs:
-  lint:
-    runs-on: ubuntu-24.04-arm
-    timeout-minutes: 10
-    env:
-      CC: clang
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
+  # lint:
+  #   runs-on: ubuntu-24.04-arm
+  #   timeout-minutes: 10
+  #   env:
+  #     CC: clang
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         persist-credentials: false
+  #
+  #     - uses: ./.github/actions/setup
+  #
+  #     - name: Install stylua
+  #       run: |
+  #         wget --directory-prefix="$BIN_DIR" https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-aarch64.zip
+  #         (cd "$BIN_DIR"; unzip stylua*.zip)
+  #
+  #     - name: Install ts_query_ls
+  #       run: |
+  #         wget --directory-prefix="$BIN_DIR" https://github.com/ribru17/ts_query_ls/releases/latest/download/ts_query_ls-aarch64-unknown-linux-gnu.tar.gz
+  #         (cd "$BIN_DIR"; tar -xzvf ts_query_ls-aarch64-unknown-linux-gnu.tar.gz)
+  #
+  #     - name: Build third-party deps
+  #       run: |
+  #         cmake -S cmake.deps -B .deps -G Ninja
+  #         cmake --build .deps
+  #
+  #     - run: cmake -B build -G Ninja -D CI_LINT=ON
+  #
+  #     - if: "!cancelled()"
+  #       name: Determine if run should be aborted
+  #       id: abort_job
+  #       env:
+  #         JOB_STATUS: ${{ job.status }}
+  #       run: echo "status=${JOB_STATUS}" >> $GITHUB_OUTPUT
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: stylua
+  #       run: cmake --build build --target lintlua-stylua
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: luals
+  #       run: cmake --build build --target luals
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: luacheck
+  #       run: cmake --build build --target lintlua-luacheck
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: lintsh
+  #       run: cmake --build build --target lintsh
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: lintquery
+  #       run: cmake --build build --target lintquery
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: clint.lua
+  #       run: cmake --build build --target lintc-clint
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: clang-tidy
+  #       run: cmake --build build --target lintc-clang-tidy
+  #
+  #     - if: success() || failure() && steps.abort_job.outputs.status == 'success'
+  #       name: uncrustify
+  #       run: cmake --build build --target lintc-uncrustify
 
-      - uses: ./.github/actions/setup
-
-      - name: Install stylua
-        run: |
-          wget --directory-prefix="$BIN_DIR" https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-aarch64.zip
-          (cd "$BIN_DIR"; unzip stylua*.zip)
-
-      - name: Install ts_query_ls
-        run: |
-          wget --directory-prefix="$BIN_DIR" https://github.com/ribru17/ts_query_ls/releases/latest/download/ts_query_ls-aarch64-unknown-linux-gnu.tar.gz
-          (cd "$BIN_DIR"; tar -xzvf ts_query_ls-aarch64-unknown-linux-gnu.tar.gz)
-
-      - name: Build third-party deps
-        run: |
-          cmake -S cmake.deps -B .deps -G Ninja
-          cmake --build .deps
-
-      - run: cmake -B build -G Ninja -D CI_LINT=ON
-
-      - if: "!cancelled()"
-        name: Determine if run should be aborted
-        id: abort_job
-        env:
-          JOB_STATUS: ${{ job.status }}
-        run: echo "status=${JOB_STATUS}" >> $GITHUB_OUTPUT
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: stylua
-        run: cmake --build build --target lintlua-stylua
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: luals
-        run: cmake --build build --target luals
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: luacheck
-        run: cmake --build build --target lintlua-luacheck
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: lintsh
-        run: cmake --build build --target lintsh
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: lintquery
-        run: cmake --build build --target lintquery
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: clint.lua
-        run: cmake --build build --target lintc-clint
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: clang-tidy
-        run: cmake --build build --target lintc-clang-tidy
-
-      - if: success() || failure() && steps.abort_job.outputs.status == 'success'
-        name: uncrustify
-        run: cmake --build build --target lintc-uncrustify
-
-  clang-analyzer:
-    runs-on: ubuntu-24.04-arm
-    timeout-minutes: 20
-    env:
-      CC: clang
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
-
-      - uses: ./.github/actions/setup
-      - name: Build third-party deps
-        run: |
-          cmake -S cmake.deps --preset ci
-          cmake --build .deps
-          cmake --preset ci
-      - run: cmake --build build --target clang-analyzer
+  # clang-analyzer:
+  #   runs-on: ubuntu-24.04-arm
+  #   timeout-minutes: 20
+  #   env:
+  #     CC: clang
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         persist-credentials: false
+  #
+  #     - uses: ./.github/actions/setup
+  #     - name: Build third-party deps
+  #       run: |
+  #         cmake -S cmake.deps --preset ci
+  #         cmake --build .deps
+  #         cmake --preset ci
+  #     - run: cmake --build build --target clang-analyzer
 
   posix:
     name: ${{ matrix.build.os }} ${{ matrix.build.flavor }} ${{ matrix.build.cc }} ${{ matrix.test }}
@@ -128,15 +128,15 @@ jobs:
         # or if github introduces a wildcard for required checks in the future.
         build:
           [
-            { runner: ubuntu-24.04, os: ubuntu, flavor: asan, cc: clang, flags: -D ENABLE_ASAN_UBSAN=ON },
-            { runner: ubuntu-24.04, os: ubuntu, flavor: tsan, cc: clang, flags: -D ENABLE_TSAN=ON },
-            { runner: ubuntu-24.04, os: ubuntu, flavor: release, cc: gcc, flags: -D CMAKE_BUILD_TYPE=Release -D ENABLE_TRANSLATIONS=ON },
-            { runner: ubuntu-24.04-arm, os: ubuntu, flavor: arm, cc: clang, flags: -D CMAKE_BUILD_TYPE=RelWithDebInfo },
-            { runner: macos-15-intel, os: macos, flavor: intel, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
-            { runner: macos-26, os: macos, flavor: arm, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
+            # { runner: ubuntu-24.04, os: ubuntu, flavor: asan, cc: clang, flags: -D ENABLE_ASAN_UBSAN=ON },
+            # { runner: ubuntu-24.04, os: ubuntu, flavor: tsan, cc: clang, flags: -D ENABLE_TSAN=ON },
+            # { runner: ubuntu-24.04, os: ubuntu, flavor: release, cc: gcc, flags: -D CMAKE_BUILD_TYPE=Release -D ENABLE_TRANSLATIONS=ON },
+            # { runner: ubuntu-24.04-arm, os: ubuntu, flavor: arm, cc: clang, flags: -D CMAKE_BUILD_TYPE=RelWithDebInfo },
+            # { runner: macos-15-intel, os: macos, flavor: intel, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
+            # { runner: macos-26, os: macos, flavor: arm, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
             { runner: ubuntu-24.04, os: ubuntu, flavor: puc-lua, cc: gcc, deps_flags: -D USE_BUNDLED_LUAJIT=OFF -D USE_BUNDLED_LUA=ON, flags: -D PREFER_LUA=ON },
           ]
-        test: [unittest, functionaltest, oldtest]
+        test: [functionaltest]
         exclude:
           - test: unittest
             build: { flavor: tsan }
@@ -203,11 +203,7 @@ jobs:
           TEST_TIMEOUT: 600
         run: |
           set +e
-          # `-k 0` tells ninja to continue running all targets even if some fail.
-          cmake --build build --target functionaltest-parallel -j 2 -- -k 0
-          exit_code="$?"
-          cmake --build build --target functionaltest-summary
-          exit "$exit_code"
+          TEST_FILE=test/functional/treesitter/select_spec.lua make functionaltest
 
       - if: ${{ matrix.test == 'oldtest' }}
         name: oldtest
@@ -246,104 +242,104 @@ jobs:
         run: cat $(find "$LOG_DIR" -type f)
 
   # TODO: matrixify
-  zig-build-linux:
-    runs-on: ubuntu-24.04
-    timeout-minutes: 45
-    name: build using zig build (linux)
-    env:
-      OPTS: -Doptimize=ReleaseSafe
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
+  # zig-build-linux:
+  #   runs-on: ubuntu-24.04
+  #   timeout-minutes: 45
+  #   name: build using zig build (linux)
+  #   env:
+  #     OPTS: -Doptimize=ReleaseSafe
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         persist-credentials: false
+  #
+  #     - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
+  #       with:
+  #         version: 0.15.2
+  #     - run: sudo apt-get install -y inotify-tools
+  #
+  #     - run: zig build $OPTS test_nlua0
+  #     - run: zig build $OPTS nvim_bin && ./zig-out/bin/nvim --version
+  #     - run: zig build $OPTS unittest
+  #     - run: zig build $OPTS functionaltest
+  #     # `zig build` uses a lua script for doctags in order to support cross-compiling
+  #     # compare with the builtin generator that they match
+  #     - run: cd runtime; ../zig-out/bin/nvim -u NONE -i NONE -e --headless -c "helptags ++t doc" -c quit
+  #     - run: diff -u runtime/doc/tags zig-out/runtime/doc/tags
 
-      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
-        with:
-          version: 0.15.2
-      - run: sudo apt-get install -y inotify-tools
+  # zig-build-macos-15:
+  #   runs-on: macos-15
+  #   timeout-minutes: 45
+  #   name: build using zig build (macos 15)
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         persist-credentials: false
+  #
+  #     - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
+  #       with:
+  #         version: 0.15.2
+  #
+  #     - run: zig build test_nlua0 -Dluajit=false
+  #     - run: zig build nvim_bin -Dluajit=false && ./zig-out/bin/nvim --version
+  #     - run: zig build functionaltest -Dluajit=false
 
-      - run: zig build $OPTS test_nlua0
-      - run: zig build $OPTS nvim_bin && ./zig-out/bin/nvim --version
-      - run: zig build $OPTS unittest
-      - run: zig build $OPTS functionaltest
-      # `zig build` uses a lua script for doctags in order to support cross-compiling
-      # compare with the builtin generator that they match
-      - run: cd runtime; ../zig-out/bin/nvim -u NONE -i NONE -e --headless -c "helptags ++t doc" -c quit
-      - run: diff -u runtime/doc/tags zig-out/runtime/doc/tags
+  # zig-build-windows:
+  #   runs-on: windows-2025
+  #   timeout-minutes: 45
+  #   name: build using zig build (windows)
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         persist-credentials: false
+  #
+  #     - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
+  #       with:
+  #         version: 0.15.2
+  #
+  #     - run: zig build test_nlua0
+  #     - run: zig build nvim_bin
+  #     - run: ./zig-out/bin/nvim --version
+  #     # TODO: support entire test suite
+  #     - run: zig build functionaltest -- test/functional/api/buffer_spec.lua
 
-  zig-build-macos-15:
-    runs-on: macos-15
-    timeout-minutes: 45
-    name: build using zig build (macos 15)
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
-
-      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
-        with:
-          version: 0.15.2
-
-      - run: zig build test_nlua0 -Dluajit=false
-      - run: zig build nvim_bin -Dluajit=false && ./zig-out/bin/nvim --version
-      - run: zig build functionaltest -Dluajit=false
-
-  zig-build-windows:
-    runs-on: windows-2025
-    timeout-minutes: 45
-    name: build using zig build (windows)
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
-
-      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
-        with:
-          version: 0.15.2
-
-      - run: zig build test_nlua0
-      - run: zig build nvim_bin
-      - run: ./zig-out/bin/nvim --version
-      # TODO: support entire test suite
-      - run: zig build functionaltest -- test/functional/api/buffer_spec.lua
-
-  windows:
-    uses: ./.github/workflows/test_windows.yml
-
-  with-external-deps:
-    runs-on: ubuntu-24.04-arm
-    timeout-minutes: 10
-    env:
-      CC: gcc
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
-
-      - uses: ./.github/actions/setup
-
-      - name: Install dependencies
-        run: |
-          sudo add-apt-repository ppa:neovim-ppa/stable
-          sudo apt-get install -y \
-            libluajit-5.1-dev \
-            libunibilium-dev \
-            libuv1-dev \
-            lua-filesystem \
-            lua-lpeg \
-            luajit \
-            lua-luv-dev
-            # libtree-sitter-dev \
-
-            # Remove comments from packages once we start using these external
-            # dependencies.
-
-      - name: Build third-party deps
-        run: |
-          cmake -S cmake.deps --preset external_deps
-          cmake --build .deps
-
-      - name: Build
-        run: |
-          cmake --preset ci
-          cmake --build build
+  # windows:
+  #   uses: ./.github/workflows/test_windows.yml
+  #
+  # with-external-deps:
+  #   runs-on: ubuntu-24.04-arm
+  #   timeout-minutes: 10
+  #   env:
+  #     CC: gcc
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         persist-credentials: false
+  #
+  #     - uses: ./.github/actions/setup
+  #
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo add-apt-repository ppa:neovim-ppa/stable
+  #         sudo apt-get install -y \
+  #           libluajit-5.1-dev \
+  #           libunibilium-dev \
+  #           libuv1-dev \
+  #           lua-filesystem \
+  #           lua-lpeg \
+  #           luajit \
+  #           lua-luv-dev
+  #           # libtree-sitter-dev \
+  #
+  #           # Remove comments from packages once we start using these external
+  #           # dependencies.
+  #
+  #     - name: Build third-party deps
+  #       run: |
+  #         cmake -S cmake.deps --preset external_deps
+  #         cmake --build .deps
+  #
+  #     - name: Build
+  #       run: |
+  #         cmake --preset ci
+  #         cmake --build build
