M .github/workflows/test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -116,130 +116,130 @@ jobs:
   #         cmake --preset ci
   #     - run: cmake --build build --target clang-analyzer
 
-  posix:
-    name: ${{ matrix.build.os }} ${{ matrix.build.flavor }} ${{ matrix.build.cc }} ${{ matrix.test }}
-    strategy:
-      fail-fast: false
-      matrix:
-        # The `os` field is not needed to differentiate between the different
-        # matrix builds. It is needed to not change the required checks (which
-        # uses jobs names) each time we bump the runner version. It may be
-        # possible to remove if we e.g. start using `-latest` runner versions
-        # or if github introduces a wildcard for required checks in the future.
-        build:
-          [
-            # { runner: ubuntu-24.04, os: ubuntu, flavor: asan, cc: clang, flags: -D ENABLE_ASAN_UBSAN=ON },
-            # { runner: ubuntu-24.04, os: ubuntu, flavor: tsan, cc: clang, flags: -D ENABLE_TSAN=ON },
-            # { runner: ubuntu-24.04, os: ubuntu, flavor: release, cc: gcc, flags: -D CMAKE_BUILD_TYPE=Release -D ENABLE_TRANSLATIONS=ON },
-            # { runner: ubuntu-24.04-arm, os: ubuntu, flavor: arm, cc: clang, flags: -D CMAKE_BUILD_TYPE=RelWithDebInfo },
-            # { runner: macos-15-intel, os: macos, flavor: intel, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
-            # { runner: macos-26, os: macos, flavor: arm, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
-            { runner: ubuntu-24.04, os: ubuntu, flavor: puc-lua, cc: gcc, deps_flags: -D USE_BUNDLED_LUAJIT=OFF -D USE_BUNDLED_LUA=ON, flags: -D PREFER_LUA=ON },
-          ]
-        test: [functionaltest]
-        exclude:
-          - test: unittest
-            build: { flavor: tsan }
-          - test: unittest
-            build: { flavor: puc-lua }
-          - test: oldtest
-            build: { flavor: tsan }
-          - test: oldtest
-            build: { runner: ubuntu-24.04-arm }
-    runs-on: ${{ matrix.build.runner }}
-    timeout-minutes: 45
-    env:
-      CC: ${{ matrix.build.cc }}
-      NVIM_TEST_INTEG: ${{ matrix.build.flavor == 'release' && '1' || '0' }}
-    steps:
-      - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
-
-      - uses: ./.github/actions/setup
-        with:
-          install_flags: "--test"
-
-      - name: Create log dir
-        run: mkdir -p "$LOG_DIR"
-
-      - if: ${{ matrix.test != 'unittest' }}
-        name: Set up interpreter packages
-        run: |
-          echo "Install neovim RubyGem."
-          gem install --no-document --bindir "$BIN_DIR" --user-install --pre neovim
-
-          sudo cpanm -n Neovim::Ext || cat "$HOME/.cpanm/build.log"
-          perl -W -e 'use Neovim::Ext; print $Neovim::Ext::VERSION'
-
-      - name: Remove .git directory
-        if: ${{ matrix.build.os == 'ubuntu' }}
-        run: cmake -E rm -rf -- .git
-
-      - name: Build third-party deps
-        env:
-          BUILD_DEPS_FLAGS: ${{ matrix.build.deps_flags }}
-        run: |
-          cmake -S cmake.deps --preset ci -D CMAKE_BUILD_TYPE=Debug $BUILD_DEPS_FLAGS
-          cmake --build .deps
-
-      - name: Build
-        env:
-          BUILD_FLAGS: ${{ matrix.build.flags }}
-        run: |
-          cmake --preset ci -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_PREFIX $BUILD_FLAGS
-          cmake --build build
-
-      - if: ${{ matrix.test == 'unittest' }}
-        name: unittest
-        timeout-minutes: 20
-        run: cmake --build build --target unittest
-
-      - if: ${{ matrix.test == 'functionaltest' }}
-        name: functionaltest
-        timeout-minutes: 20
-        env:
-          # With parallel tests, use shorter timeout for a single group.
-          TEST_TIMEOUT: 600
-        run: |
-          set +e
-          TEST_FILE=test/functional/treesitter/select_spec.lua make functionaltest
-
-      - if: ${{ matrix.test == 'oldtest' }}
-        name: oldtest
-        timeout-minutes: 20
-        run: make -C test/old/testdir NVIM_PRG=$(realpath build)/bin/nvim
-
-      - name: Install
-        run: |
-          cmake --install build
-          "$INSTALL_PREFIX/bin/nvim" -V1 --version
-          if ! "$INSTALL_PREFIX/bin/nvim" -u NONE -e -c ':help' -c ':qall'; then
-            echo "Running ':help' in the installed nvim failed."
-            echo "Maybe the helptags have not been generated properly."
-            echo 'Failed running :help'
-            exit 1
-          fi
-
-          # Check that all runtime files were installed
-          for file in $(git -C runtime ls-files '*.vim' '*.ps' '*.dict' '*.py' '*.tutor' '*.awk' '*.sh' '*.bat'); do
-            if ! test -e "$INSTALL_PREFIX/share/nvim/runtime/$file"; then
-              printf "It appears that %s is not installed." "$file"
-              exit 1
-            fi
-          done
-
-          # Check that generated syntax file has function names, #5060.
-          genvimsynf=syntax/vim/generated.vim
-          gpat='syn keyword vimFuncName .*eval'
-          if ! grep -q "$gpat" "$INSTALL_PREFIX/share/nvim/runtime/$genvimsynf"; then
-            echo "It appears that $genvimsynf does not contain $gpat."
-            exit 1
-          fi
-
-      - if: '!cancelled()'
-        name: Show logs
-        run: cat $(find "$LOG_DIR" -type f)
+  # posix:
+  #   name: ${{ matrix.build.os }} ${{ matrix.build.flavor }} ${{ matrix.build.cc }} ${{ matrix.test }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # The `os` field is not needed to differentiate between the different
+  #       # matrix builds. It is needed to not change the required checks (which
+  #       # uses jobs names) each time we bump the runner version. It may be
+  #       # possible to remove if we e.g. start using `-latest` runner versions
+  #       # or if github introduces a wildcard for required checks in the future.
+  #       build:
+  #         [
+  #           # { runner: ubuntu-24.04, os: ubuntu, flavor: asan, cc: clang, flags: -D ENABLE_ASAN_UBSAN=ON },
+  #           # { runner: ubuntu-24.04, os: ubuntu, flavor: tsan, cc: clang, flags: -D ENABLE_TSAN=ON },
+  #           # { runner: ubuntu-24.04, os: ubuntu, flavor: release, cc: gcc, flags: -D CMAKE_BUILD_TYPE=Release -D ENABLE_TRANSLATIONS=ON },
+  #           # { runner: ubuntu-24.04-arm, os: ubuntu, flavor: arm, cc: clang, flags: -D CMAKE_BUILD_TYPE=RelWithDebInfo },
+  #           # { runner: macos-15-intel, os: macos, flavor: intel, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
+  #           # { runner: macos-26, os: macos, flavor: arm, cc: clang, flags: -D CMAKE_FIND_FRAMEWORK=NEVER, deps_flags: -D CMAKE_FIND_FRAMEWORK=NEVER },
+  #           { runner: ubuntu-24.04, os: ubuntu, flavor: puc-lua, cc: gcc, deps_flags: -D USE_BUNDLED_LUAJIT=OFF -D USE_BUNDLED_LUA=ON, flags: -D PREFER_LUA=ON },
+  #         ]
+  #       test: [functionaltest]
+  #       exclude:
+  #         - test: unittest
+  #           build: { flavor: tsan }
+  #         - test: unittest
+  #           build: { flavor: puc-lua }
+  #         - test: oldtest
+  #           build: { flavor: tsan }
+  #         - test: oldtest
+  #           build: { runner: ubuntu-24.04-arm }
+  #   runs-on: ${{ matrix.build.runner }}
+  #   timeout-minutes: 45
+  #   env:
+  #     CC: ${{ matrix.build.cc }}
+  #     NVIM_TEST_INTEG: ${{ matrix.build.flavor == 'release' && '1' || '0' }}
+  #   steps:
+  #     - uses: actions/checkout@v6
+  #       with:
+  #         persist-credentials: false
+  #
+  #     - uses: ./.github/actions/setup
+  #       with:
+  #         install_flags: "--test"
+  #
+  #     - name: Create log dir
+  #       run: mkdir -p "$LOG_DIR"
+  #
+  #     - if: ${{ matrix.test != 'unittest' }}
+  #       name: Set up interpreter packages
+  #       run: |
+  #         echo "Install neovim RubyGem."
+  #         gem install --no-document --bindir "$BIN_DIR" --user-install --pre neovim
+  #
+  #         sudo cpanm -n Neovim::Ext || cat "$HOME/.cpanm/build.log"
+  #         perl -W -e 'use Neovim::Ext; print $Neovim::Ext::VERSION'
+  #
+  #     - name: Remove .git directory
+  #       if: ${{ matrix.build.os == 'ubuntu' }}
+  #       run: cmake -E rm -rf -- .git
+  #
+  #     - name: Build third-party deps
+  #       env:
+  #         BUILD_DEPS_FLAGS: ${{ matrix.build.deps_flags }}
+  #       run: |
+  #         cmake -S cmake.deps --preset ci -D CMAKE_BUILD_TYPE=Debug $BUILD_DEPS_FLAGS
+  #         cmake --build .deps
+  #
+  #     - name: Build
+  #       env:
+  #         BUILD_FLAGS: ${{ matrix.build.flags }}
+  #       run: |
+  #         cmake --preset ci -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_PREFIX $BUILD_FLAGS
+  #         cmake --build build
+  #
+  #     - if: ${{ matrix.test == 'unittest' }}
+  #       name: unittest
+  #       timeout-minutes: 20
+  #       run: cmake --build build --target unittest
+  #
+  #     - if: ${{ matrix.test == 'functionaltest' }}
+  #       name: functionaltest
+  #       timeout-minutes: 20
+  #       env:
+  #         # With parallel tests, use shorter timeout for a single group.
+  #         TEST_TIMEOUT: 600
+  #       run: |
+  #         set +e
+  #         TEST_FILE=test/functional/treesitter/select_spec.lua make functionaltest
+  #
+  #     - if: ${{ matrix.test == 'oldtest' }}
+  #       name: oldtest
+  #       timeout-minutes: 20
+  #       run: make -C test/old/testdir NVIM_PRG=$(realpath build)/bin/nvim
+  #
+  #     - name: Install
+  #       run: |
+  #         cmake --install build
+  #         "$INSTALL_PREFIX/bin/nvim" -V1 --version
+  #         if ! "$INSTALL_PREFIX/bin/nvim" -u NONE -e -c ':help' -c ':qall'; then
+  #           echo "Running ':help' in the installed nvim failed."
+  #           echo "Maybe the helptags have not been generated properly."
+  #           echo 'Failed running :help'
+  #           exit 1
+  #         fi
+  #
+  #         # Check that all runtime files were installed
+  #         for file in $(git -C runtime ls-files '*.vim' '*.ps' '*.dict' '*.py' '*.tutor' '*.awk' '*.sh' '*.bat'); do
+  #           if ! test -e "$INSTALL_PREFIX/share/nvim/runtime/$file"; then
+  #             printf "It appears that %s is not installed." "$file"
+  #             exit 1
+  #           fi
+  #         done
+  #
+  #         # Check that generated syntax file has function names, #5060.
+  #         genvimsynf=syntax/vim/generated.vim
+  #         gpat='syn keyword vimFuncName .*eval'
+  #         if ! grep -q "$gpat" "$INSTALL_PREFIX/share/nvim/runtime/$genvimsynf"; then
+  #           echo "It appears that $genvimsynf does not contain $gpat."
+  #           exit 1
+  #         fi
+  #
+  #     - if: '!cancelled()'
+  #       name: Show logs
+  #       run: cat $(find "$LOG_DIR" -type f)
 
   # TODO: matrixify
   # zig-build-linux:
@@ -267,41 +267,41 @@ jobs:
   #     - run: cd runtime; ../zig-out/bin/nvim -u NONE -i NONE -e --headless -c "helptags ++t doc" -c quit
   #     - run: diff -u runtime/doc/tags zig-out/runtime/doc/tags
 
-  # zig-build-macos-15:
-  #   runs-on: macos-15
-  #   timeout-minutes: 45
-  #   name: build using zig build (macos 15)
-  #   steps:
-  #     - uses: actions/checkout@v6
-  #       with:
-  #         persist-credentials: false
-  #
-  #     - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
-  #       with:
-  #         version: 0.15.2
-  #
-  #     - run: zig build test_nlua0 -Dluajit=false
-  #     - run: zig build nvim_bin -Dluajit=false && ./zig-out/bin/nvim --version
-  #     - run: zig build functionaltest -Dluajit=false
+  zig-build-macos-15:
+    runs-on: macos-15
+    timeout-minutes: 45
+    name: build using zig build (macos 15)
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
 
-  # zig-build-windows:
-  #   runs-on: windows-2025
-  #   timeout-minutes: 45
-  #   name: build using zig build (windows)
-  #   steps:
-  #     - uses: actions/checkout@v6
-  #       with:
-  #         persist-credentials: false
-  #
-  #     - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
-  #       with:
-  #         version: 0.15.2
-  #
-  #     - run: zig build test_nlua0
-  #     - run: zig build nvim_bin
-  #     - run: ./zig-out/bin/nvim --version
-  #     # TODO: support entire test suite
-  #     - run: zig build functionaltest -- test/functional/api/buffer_spec.lua
+      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
+        with:
+          version: 0.15.2
+
+      - run: zig build test_nlua0 -Dluajit=false
+      - run: zig build nvim_bin -Dluajit=false && ./zig-out/bin/nvim --version
+      - run: zig build functionaltest -Dluajit=false
+
+  zig-build-windows:
+    runs-on: windows-2025
+    timeout-minutes: 45
+    name: build using zig build (windows)
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+
+      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
+        with:
+          version: 0.15.2
+
+      - run: zig build test_nlua0
+      - run: zig build nvim_bin
+      - run: ./zig-out/bin/nvim --version
+      # TODO: support entire test suite
+      - run: zig build functionaltest -- test/functional/api/buffer_spec.lua
 
   # windows:
   #   uses: ./.github/workflows/test_windows.yml
